baseURL = 'https://compassionate-rosalind-ba0065.netlify.app/'
languageCode = 'en-us'
title = 'The Color Site'
description = "My new homepage"
theme = "paper"

#metadata for doc head
#description = "My new homepage"
#keywords = "homepage, blog, mood" #not sure
#images = [""]

#"disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments

# Set disableReadOtherPosts to true in order to hide the links to other posts.
#disableReadOtherPosts = false

# Enable sharing buttons, if you like
#enableSharingButtons = true

defaultContentLanguage = 'en'
enableEmoji = true

[params]
  disableHLJS = true                         # don't use highlight.js
  github = 'MBa-Riga/Jamstack-Color-Site'                  # github.com/YOUR_GITHUB_ID




[taxonomies]
    category = "categories"
    tag      = "tags"


[menu]
  # And you can even create generic menu
  [[menu.main]]
    identifier = "article"
    name       = "Article"
    url        = "/article/" 
    weight     = "2"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/post/"
    weight     = "3"

    [[menu.main]]
    identifier = "mood"
    name       = "Today's Colors"
    url        = "/mood/mood"
    weight     = "4"

    [[menu.main]]
    identifier = "all-color"
    name       = "All the Colors"
    url        = "/mood/"
    weight     = "1"


    ########################
[languages] 

    [languages.en]
        weight = 1   
    [languages.lv]
        weight = 2
    [languages.fr]
        weight = 3