baseURL = 'https://mba-the-color-site.netlify.app'
languageCode = 'en-us'
title = 'The Color Site'
description = "My new homepage"
theme = "paper"


defaultContentLanguage = 'en'
enableEmoji = true

[params]
  disableHLJS = true                         # don't use highlight.js
  github = 'MBa-Riga/Jamstack-Color-Site'                  # github.com/YOUR_GITHUB_ID


[taxonomies]
    category = "categories"
    tag      = "tags"


[menu]
  # And you can even create generic menu
  [[menu.main]]
    identifier = "article"
    name       = "Article"
    url        = "/article/" 
    weight     = "2"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/post/"
    weight     = "3"

    [[menu.main]]
    identifier = "mood"
    name       = "Today's Colors"
    url        = "/mood/mood"
    weight     = "4"

    [[menu.main]]
    identifier = "all-color"
    name       = "All the Colors"
    url        = "/all-color/all-color"
    weight     = "1"

    [[menu.main]]
    identifier = "aboutme"
    name       = "About me ! "
    url        = "/post/About-me"
    weight     = "6"

    [[menu.main]]
    identifier = "study"
    name       = "Professional experience "
    url        = "/study"
    weight     = "5"